const exercises = [
    { name: "Seated DB Shrugs", muscleGroup: ["shoulders", "back"], type: "Dumbbell" },
    { name: "BB Silverback Shrugs", muscleGroup: ["shoulders", "back"], type: "Barbell" },
    { name: "Silverback Shrug", muscleGroup: ["shoulders", "back"], type: "Machine" },
    { name: "Upright Row", muscleGroup: ["shoulders", "arms"], type: "Machine" },
    { name: "BB Overhead Press", muscleGroup: ["shoulders", "arms"], type: "Barbell" },
    { name: "Seated DB Shoulder Press", muscleGroup: ["shoulders", "arms"], type: "Dumbbell" },
    { name: "DB Bicep Curl", muscleGroup: ["arms"], type: "Dumbbell" },
    { name: "Hammer Curl", muscleGroup: ["arms"], type: "Dumbbell" },
    { name: "Deadlift", muscleGroup: ["back", "upper legs", "lower legs"], type: "Barbell" },
    { name: "Lat Pull Down", muscleGroup: ["back", "arms"], type: "Machine" },
    { name: "Cable Chest Fly", muscleGroup: ["chest"], type: "Machine" },
    { name: "BB Back Pull", muscleGroup: ["back", "upper legs"], type: "Barbell" },
    { name: "Machine Shoulder Press", muscleGroup: ["shoulders", "arms"], type: "Machine" },
    { name: "BB Bench Press", muscleGroup: ["chest", "arms", "shoulders"], type: "Barbell" },
    { name: "BB Incline Bench Press", muscleGroup: ["chest", "arms", "shoulders"], type: "Barbell" },
    { name: "DB Chest Fly", muscleGroup: ["chest"], type: "Dumbbell" },
    { name: "DB Bench Press", muscleGroup: ["chest", "arms", "shoulders"], type: "Dumbbell" },
    { name: "DB Incline Bench Press", muscleGroup: ["chest", "arms", "shoulders"], type: "Dumbbell" },
    { name: "Crunch Machine", muscleGroup: ["back"], type: "Machine" },
    { name: "DB Sit Up", muscleGroup: ["back"], type: "Dumbbell" },
    { name: "Squat", muscleGroup: ["upper legs", "lower legs", "back"], type: "Barbell" },
    { name: "Wide Squat", muscleGroup: ["upper legs", "lower legs", "back"], type: "Barbell" },
    { name: "Leg Extensions", muscleGroup: ["upper legs"], type: "Machine" },
    { name: "Lying Leg Curls", muscleGroup: ["upper legs"], type: "Machine" },
    { name: "Cable Rows", muscleGroup: ["back", "arms"], type: "Machine" },
    { name: "Tricep Curls", muscleGroup: ["arms"], type: "Machine" },
    { name: "Military Press", muscleGroup: ["shoulders", "arms"], type: "Barbell" },
    { name: "Jump Squat", muscleGroup: ["upper legs", "lower legs", "back"], type: "Dumbbell" },
    { name: "Narrow DB Bench Press", muscleGroup: ["chest", "arms", "shoulders"], type: "Dumbbell" },
    { name: "DB Good Morning", muscleGroup: ["back", "upper legs"], type: "Dumbbell" },
    { name: "BB Calf Raise", muscleGroup: ["lower legs"], type: "Barbell" },
    { name: "Machine Chest Fly", muscleGroup: ["chest"], type: "Machine" },
    { name: "High to Low Chest Fly", muscleGroup: ["chest"], type: "Dumbbell" },
    { name: "Blaster Curls", muscleGroup: ["arms"], type: "Dumbbell" },
    { name: "Incline Chest Fly", muscleGroup: ["chest"], type: "Dumbbell" },
    { name: "Zottman Curls", muscleGroup: ["arms"], type: "Dumbbell" },
    { name: "Machine Press", muscleGroup: ["chest", "arms", "shoulders"], type: "Machine" },
    { name: "Incline Machine Press", muscleGroup: ["chest", "arms", "shoulders"], type: "Machine" },
    { name: "Straight Arm Pushdown", muscleGroup: ["arms", "shoulders"], type: "Machine" },
    { name: "Cable Rope Face Pulls", muscleGroup: ["shoulders", "arms"], type: "Machine" },
    { name: "BB Rows", muscleGroup: ["back", "arms"], type: "Barbell" },
    { name: "DB Wide Curls", muscleGroup: ["arms"], type: "Dumbbell" },
    { name: "BB Curls", muscleGroup: ["arms"], type: "Barbell" },
    { name: "BB Wide Curls", muscleGroup: ["arms"], type: "Barbell" },
    { name: "DB Reverse Curl", muscleGroup: ["arms"], type: "Dumbbell" },
    { name: "BB Reverse Curl", muscleGroup: ["arms"], type: "Barbell" },
    { name: "Low Cable Chest Fly", muscleGroup: ["chest"], type: "Machine" },
    { name: "Narrow Squat", muscleGroup: ["upper legs", "lower legs", "back"], type: "Barbell" },
    { name: "Sumo Deadlift", muscleGroup: ["back", "upper legs", "lower legs"], type: "Barbell" },
    { name: "BB Upright Row", muscleGroup: ["shoulders", "arms"], type: "Barbell" },
    { name: "DB Upright Row", muscleGroup: ["shoulders", "arms"], type: "Dumbbell" },
    { name: "DB Fly", muscleGroup: ["shoulders"], type: "Dumbbell" },
    { name: "DB Rows", muscleGroup: ["back", "arms"], type: "Dumbbell" },
    { name: "Seated Leg Curls", muscleGroup: ["upper legs"], type: "Machine" },
    { name: "BB Good Morning", muscleGroup: ["back", "upper legs"], type: "Barbell" },
    { name: "BB Bulgarian Split Squat", muscleGroup: ["upper legs", "lower legs", "back"], type: "Barbell" },
    { name: "DB Bulgarian Split Squat", muscleGroup: ["upper legs", "lower legs", "back"], type: "Dumbbell" },
    { name: "Cable Glute Kickback", muscleGroup: ["back"], type: "Machine" },
    { name: "Cable Back Pull", muscleGroup: ["back", "upper legs"], type: "Machine" },
    { name: "Cable Hip Abduction", muscleGroup: ["upper legs"], type: "Machine" },
    { name: "DB Back Pull", muscleGroup: ["back", "upper legs"], type: "Dumbbell" },
    { name: "Cable Leg Curl", muscleGroup: ["upper legs"], type: "Machine" },
    { name: "DB Calf Raise", muscleGroup: ["lower legs"], type: "Dumbbell" },
    { name: "DB Squat", muscleGroup: ["upper legs", "lower legs", "back"], type: "Dumbbell" },
    { name: "DB Wide Squat", muscleGroup: ["upper legs", "lower legs", "back"], type: "Dumbbell" },
    { name: "DB Narrow Squat", muscleGroup: ["upper legs", "lower legs", "back"], type: "Dumbbell" },
    { name: "DB Tricep Dips", muscleGroup: ["arms"], type: "Dumbbell" }
];

module.exports = exercises;